#ouvir na porta padrão MQTT-1883 em todas as interfaces de rede do container
listener 1883 0.0.0.0

#config de seguranca
allow_anonymous false
password_file /mosquitto/config/passwd

#config de persistencia
persistence true
persistence_location /mosquitto/data/

#config de Logs para observabilidade
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information